"""The fitted simulator: does the frozen table still behave like the fit?

The table is generated by ``analysis/export_response.py`` from a fit that needs
scipy and the 43 h sweep, neither of which the test suite has.  So what is
pinned here is everything downstream of the table -- the inversion, the
integrator, the clamping -- plus a handful of values off the fitted curve
itself, which is how a regenerated table that has quietly changed shape
announces itself.
"""

import math
import random

import pytest

from ltspm3.model.fitted_response import (
    FittedResponse,
    T_MAX_K,
    T_MIN_K,
    fitted_cryostat,
    heat_capacity_j_per_k,
    percent_for_power,
    power_w,
    steady_power_w,
    steady_temperature_k,
    tau_s,
)


def settle(r: FittedResponse, seconds: float, dt: float = 4.0) -> float:
    for _ in range(int(seconds / dt)):
        r.advance(dt)
    return r.temperature


# -- the actuator, which is exact ------------------------------------------

def test_the_heater_is_a_resistor_and_the_arithmetic_round_trips():
    for pct in (0.0, 7.187, 48.0, 63.701, 70.0):
        assert percent_for_power(power_w(pct)) == pytest.approx(pct, abs=1e-9)
    # P goes as the square: doubling the percent quadruples the watts.
    assert power_w(60.0) / power_w(30.0) == pytest.approx(4.0)


# -- the steady state ------------------------------------------------------

#: Off the fitted curve, 2026-09-05.  Not round numbers and not from anybody's
#: memory: these are what `analysis/plan_sweep.py` prints, and they are the
#: whole reason the old two-pole response was replaced -- it puts 56.06% at
#: 56 K where the fit and the 43 h sweep put it at 38.7 K.
FITTED_POINTS = [
    (7.187, 5.30), (24.380, 9.93), (44.530, 20.0), (52.709, 30.0),
    (56.425, 40.0), (60.597, 70.0), (63.701, 110.0), (66.724, 150.0),
]


@pytest.mark.parametrize("pct,kelvin", FITTED_POINTS)
def test_the_steady_state_is_the_fitted_one(pct, kelvin):
    assert FittedResponse().steady_state(pct) == pytest.approx(kelvin, abs=0.05)


@pytest.mark.parametrize("pct,kelvin", FITTED_POINTS)
def test_and_it_inverts(pct, kelvin):
    """Round-tripped rather than checked against the kelvin above, which is
    rounded to a hundredth and is not a fixed point of anything."""
    r = FittedResponse()
    assert r.percent_for(r.steady_state(pct)) == pytest.approx(pct, abs=1e-6)
    assert r.percent_for(kelvin) == pytest.approx(pct, abs=0.05)


def test_the_steady_state_is_monotone_in_the_output():
    r = FittedResponse()
    temps = [r.steady_state(u) for u in range(0, 71)]
    assert temps == sorted(temps)


def test_the_gain_climbs_by_a_factor_of_forty_across_the_range():
    """0.3 K/% at 10 K and 13 K/% at 110 K is the fact that makes this cryostat
    hard to control, and it is the one a constant-gain model throws away."""
    r = FittedResponse()
    assert r.local_gain(r.percent_for(10.0)) == pytest.approx(0.3, abs=0.1)
    assert r.local_gain(r.percent_for(110.0)) == pytest.approx(13.2, abs=0.5)


def test_q_and_t_invert_each_other():
    for kelvin in (6.0, 12.0, 40.0, 90.0, 150.0):
        assert steady_temperature_k(steady_power_w(kelvin)) == pytest.approx(
            kelvin, rel=1e-6)


# -- the dynamics ----------------------------------------------------------

def test_tau_spans_three_orders_of_magnitude():
    """The whole reason a fixed dwell is wrong at both ends."""
    assert tau_s(10.0) < 1.0
    assert tau_s(40.0) == pytest.approx(36, rel=0.15)
    assert tau_s(110.0) == pytest.approx(489, rel=0.1)
    assert tau_s(10.0) * 400 < tau_s(110.0)


def test_the_heat_capacity_falls_steeply_toward_the_cold_end():
    assert heat_capacity_j_per_k(10.0) < heat_capacity_j_per_k(100.0) / 50


def test_a_held_output_settles_on_its_own_steady_state():
    r = FittedResponse(start_pct=0.0)
    r.pct = 63.701
    settle(r, 20 * tau_s(110.0))
    assert r.temperature == pytest.approx(r.steady_state(63.701), abs=0.01)


def test_one_time_constant_covers_the_usual_fraction_of_the_step():
    """It is a relaxation, so 1 - 1/e of the way in one tau -- and this is what
    the sweep's own pole fit is going to read back off the dwell."""
    r = FittedResponse(start_pct=60.168)          # settled at about 65 K
    start = r.temperature
    r.pct = 60.801
    target = r.steady_state(60.801)
    got = settle(r, tau_s(0.5 * (start + target)), dt=1.0)
    assert (got - start) / (target - start) == pytest.approx(1 - 1 / math.e, abs=0.05)


def test_the_integrator_does_not_care_about_the_step_size():
    """Exponential Euler, so a virtual clock may take 1 s or 100 s steps.

    Not a nicety: C falls so steeply at the cold end that an explicit step goes
    unstable there long before the physics does, and the suite drives this at
    wildly varying dt.
    """
    ends = []
    for dt in (0.5, 5.0, 50.0, 200.0):
        r = FittedResponse(start_pct=56.064)
        r.pct = 60.597
        ends.append(settle(r, 4000.0, dt=dt))
    assert max(ends) - min(ends) < 0.5
    assert ends[0] == pytest.approx(FittedResponse().steady_state(60.597), abs=0.1)


def test_a_cold_rung_settles_before_the_recorder_can_see_it_move():
    """Below about 25 K tau is a few seconds, which is the recorder's own
    cadence -- so those rungs measure a steady state and cannot measure a tau,
    however long they are held."""
    r = FittedResponse(start_pct=24.380)
    r.pct = 27.411
    target = r.steady_state(27.411)
    assert settle(r, 30.0, dt=2.0) == pytest.approx(target, abs=0.01)


# -- the edges -------------------------------------------------------------

def test_the_table_clamps_instead_of_extrapolating():
    """A simulator that extrapolates a fitted curve is inventing a cryostat."""
    r = FittedResponse()
    assert r.steady_state(0.0) == pytest.approx(T_MIN_K)
    assert r.steady_state(200.0) == pytest.approx(T_MAX_K)
    r.pct = 0.0
    assert settle(r, 100000.0, dt=100.0) >= T_MIN_K


def test_zero_percent_is_zero_watts_not_a_negative_temperature():
    assert power_w(0.0) == 0.0
    assert power_w(-5.0) == 0.0


# -- the seam the simulator uses -------------------------------------------

def test_it_drops_into_the_generic_simulator_untouched():
    """`lschart` never learns this class exists -- it is duck-typed by name,
    which is invariant 1 and the reason the response is injected at all."""
    from lschart.instruments import LS218
    from lschart.instruments.sim import Sim218
    from lschart.transport import LoopbackTransport

    clock = [0.0]
    cryostat = fitted_cryostat(start_pct=60.597, time_source=lambda: clock[0])
    sim = Sim218(cryostat)
    # The fake box keeps its own idea of the output and it is the one the
    # recorder reads back, so a cryostat started at a percent has to say so
    # here too -- exactly as `SimLink` does.
    sim.analog_pct = 60.597
    inst = LS218(LoopbackTransport(sim),
                 channels={1: "Sample", 2: "Coldplate"},
                 allow_writes=True, verify_writes=False, max_output_pct=70.0)
    readings, aux = inst.read_frame()
    assert readings["Sample"].kelvin == pytest.approx(70.0, abs=0.5)
    assert aux["ls218.aout1"] == pytest.approx(60.597, abs=0.01)

    # ...and the ancillary channels follow it, which is what cross-channel
    # corroboration needs to have anything to corroborate.
    inst.set_analog_percent(63.701)
    clock[0] += 20000.0
    readings, _ = inst.read_frame()
    assert readings["Sample"].kelvin == pytest.approx(110.0, abs=0.5)
    assert readings["Coldplate"].kelvin > 8.0


def test_the_observed_reading_carries_noise_and_the_boxs_resolution():
    r = FittedResponse(start_pct=63.701)
    rng = random.Random(7)
    values = [r.observe(rng) for _ in range(200)]
    assert all(abs(v * 1000 - round(v * 1000)) < 1e-6 for v in values)   # 1 mK
    spread = max(values) - min(values)
    assert 0.0 < spread < 0.5
