"""The LTSPM3 thermal characterisation -- every number that describes the cryostat.

One package, so "the model" has an address.  Nothing here touches an
instrument; everything here is read by ``ltspm3.control`` (feedforward, the
schedule, the rate conversion, the watt residual), by the simulator, by the
tools and by the monitor.  ``analysis/`` GENERATES ``_fitted_table``; the rest
is hand-written and measured.  Stdlib only.

    thermal_response   the CD10 percent-to-kelvin curve and P(pct)
    fitted_response    the ODE fitted to the 43 h sweep, integrated from a table
    _fitted_table      GENERATED by analysis/export_response.py -- do not edit
    sim_response       the two-pole fake the control harness is calibrated to

See PID_PLAN.md section 2 for where this sits in the software model.
"""
