"""The simulated cryostat, driven by the fitted ODE instead of a two-pole lag.

``sim_response.ThermalModel`` was the best available when it was written and is
now the second best.  It carries **one** time constant -- 620 s, inferred from a
single clean step at 137 K -- onto a steady state interpolated from the CD10
percent-to-kelvin table.  The 43 h sweep of 2026-09 and the ODE fitted to it
say both halves are wrong away from that one point:

* ``tau`` is not a constant.  ``tau = C/Lambda'`` runs from **under a second at
  10 K to about 490 s at 110 K** -- a factor of a thousand, because C falls
  steeply as the cryostat cools while the link's conductance does not.
* the steady state is out by up to **17 K** in the middle, where CD10 had two
  points twenty percentage points apart and the curve between them was a power
  law doing the best it could.

Neither error is visible in a control test that sits at one temperature, which
is why this went unnoticed: at 137 K the two models agree, and that is where
almost everything was tested.  It is very visible in a *sweep*, which is the
one thing that crosses the whole range -- rehearse a 30-rung ladder against the
old response and two thirds of the rungs come back cut off mid-relaxation, none
of it telling you anything about the cryostat.

**That contradiction has since been paid.**  The programmed ladder of
2026-09-05 measured this table's predecessor low by up to 4.5 K across 40-98 K;
the refit of 2026-09-13 reconciled the two and the shipped table is 4-5 K warmer
at a given output than every number written before that date.  What remains true
is narrower and does not expire: **the LEVEL is a calibration with a shelf
life** -- handling the heater wiring moves it by up to 0.8 %, which is 3 K at
118 K -- while the SHAPE does not.  See the header of
:mod:`ltspm3.model._fitted_table` for the gauge, the window and the day it was
measured.

What the table also carries now is its own error band -- ``SIGMA_MODEL_K`` and
the rest -- and the two functions that use it, :func:`missing_power_w` and
:func:`sigma_q_w`.  Those are what the monitor and the supervisor judge the
cryostat by; see PID_PLAN.md section 3 and ``analysis/band.py``.

What this integrates
--------------------

The same equation the fit was fitted with::

    C(T) dT/dt = Q(u) - [Lambda(T) - Lambda(T_c)]

with ``Q(u) = (G V_fs u/100)^2 / R`` -- exact, the actuator chain has nothing
to fit -- and exponential Euler, ``T += g tau (1 - exp(-dt/tau))``, which is
exact for the linearised relaxation and unconditionally stable.  Stability is
not a nicety here: C falls so steeply at the cold end that an explicit step
goes unstable there long before the interesting physics does, and the tests
drive this with a virtual clock at wildly varying dt.

The four curves come from :mod:`ltspm3.model._fitted_table`, which is generated by
``analysis/export_response.py`` and checked in.  The fit itself needs scipy,
the 43 h sweep and a couple of minutes; this needs the standard library.

What it still simplifies
------------------------

**The coldplate follows the sample along its settled locus**, rather than
lagging it.  ``T_c`` is interpolated against sample temperature from the
settled dwells, so the steady state is exactly the fitted one, while during a
transient the real coldplate lags by about 175 s (``analysis/bath.py``).  That
is worth knowing before reading a simulated transient closely, and it is not
worth fixing for a rehearsal: the coldplate moves 2.3 K across the range the
sample moves 190 K over.

Outside 4.7-195 K the table **clamps**.  A simulator that quietly extrapolates
a fitted curve is inventing a cryostat, and inventing one is how a rehearsal
comes to disagree with the afternoon it was rehearsing.
"""

from __future__ import annotations

import math
import random
from bisect import bisect_right
from dataclasses import dataclass

from ._fitted_table import (
    DELTA_P_FRAC,
    DIURNAL_K,
    DRIFT_REF_W,
    DRIFT_T0,
    DRIFT_T0_UNIX,
    DRIFT_W_PER_DAY,
    GAIN,
    R_OHM,
    SIGMA_C_FRAC,
    SIGMA_MODEL_K,
    SIGMA_TINF_K,
    T_MAX_K,
    T_MIN_K,
    TABLE,
    TAU_BATH_S,
    TC_RMS_K,
    V_FS,
)

__all__ = [
    "FittedParams", "FittedResponse", "power_w", "percent_for_power",
    "conductance_w", "missing_power_w", "sigma_q_w", "sigma_q_fast_w",
    "sigma_q_terms", "FAST_TERMS",
    "bias_q_w", "days_since_gauge",
    "DELTA_P_FRAC", "DIURNAL_K", "DRIFT_REF_W", "DRIFT_T0", "DRIFT_T0_UNIX",
    "DRIFT_W_PER_DAY", "SIGMA_C_FRAC", "SIGMA_MODEL_K", "SIGMA_TINF_K",
    "TAU_BATH_S", "TC_RMS_K",
]


def power_w(pct: float) -> float:
    """Heater watts for a commanded percent.  Exact: the heater is a resistor.

    The 218's analog output is a voltage into a stable 75.5 ohm heater, so
    ``P = V^2/R`` and there is nothing here that varies with temperature or
    that anyone has to fit.  Every difficulty on this cryostat lives in T(P).
    """
    return (GAIN * V_FS * max(pct, 0.0) / 100.0) ** 2 / R_OHM


def percent_for_power(watts: float) -> float:
    if watts <= 0.0:
        return 0.0
    return 100.0 * math.sqrt(watts * R_OHM) / (GAIN * V_FS)


@dataclass
class FittedParams:
    """The parts of the simulated sensor that are not the thermal model.

    Measured by 3-point local detrending over cd9+cd10, and shared with
    ``ResponseParams`` on purpose -- the thermometer did not change when the
    model did.
    """

    noise_floor_k: float = 0.0018      # rms at low T
    noise_quadratic: float = 1.36e-6   # rms = this * T**2
    quantum_k: float = 0.001           # reported resolution


# The table, unpacked once into parallel lists.  Logs are precomputed because
# every interpolation here is log-log -- the curves are power laws over most of
# their range, and interpolating them linearly in T would put visible kinks in
# a quantity the fit went to some trouble to make smooth.
_T = [row[0] for row in TABLE]
_LOG_T = [math.log(t) for t in _T]
#: ``Q(T) = Lambda(T) - Lambda(T_c(T))``, the power that holds each temperature.
#: The table carries this **evaluated** rather than carrying Lambda, and that is
#: not an optimisation: Lambda is 2.38 W at the cold end where Q is 8 mW, so
#: reconstructing Q by subtracting two interpolated Lambdas loses five
#: significant figures -- and the T_c term falls off the bottom of any grid that
#: starts at the coldest sample temperature, because the coldplate is colder
#: still.  Doing it that way put every steady state below 8 K about 0.2 K too
#: warm, which is four times the fit's own residual.
_LOG_Q = [math.log(row[1]) for row in TABLE]
_LOG_SLOPE = [math.log(row[2]) for row in TABLE]
_LOG_CAP = [math.log(row[3]) for row in TABLE]
_TC = [row[4] for row in TABLE]


def _interp(x: float, xs: list[float], ys: list[float]) -> float:
    """Linear in the given coordinates, clamped at both ends."""
    if x <= xs[0]:
        return ys[0]
    if x >= xs[-1]:
        return ys[-1]
    i = bisect_right(xs, x) - 1
    x0, x1 = xs[i], xs[i + 1]
    y0, y1 = ys[i], ys[i + 1]
    return y0 if x1 == x0 else y0 + (y1 - y0) * (x - x0) / (x1 - x0)


def _log_interp(kelvin: float, log_ys: list[float]) -> float:
    return math.exp(_interp(math.log(max(kelvin, 1e-9)), _LOG_T, log_ys))


def lambda_slope_w_per_k(kelvin: float) -> float:
    """``Lambda'(T) = k(T) A/L``, in W/K."""
    return _log_interp(kelvin, _LOG_SLOPE)


def heat_capacity_j_per_k(kelvin: float) -> float:
    return _log_interp(kelvin, _LOG_CAP)


def coldplate_k(kelvin: float) -> float:
    """The coldplate the sample is sinking to, at this sample temperature.

    Measured, not assumed: 4.8 K with the heater off and 6.9 K at 180 K.  A
    constant bath here would put the whole 2.1 K of it into ``Lambda``.
    """
    return _interp(kelvin, _T, _TC)


def tau_s(kelvin: float) -> float:
    """The local time constant, ``C/Lambda'``.  0.01 s at 4.9 K, 619 s at 195 K."""
    slope = lambda_slope_w_per_k(kelvin)
    return heat_capacity_j_per_k(kelvin) / (slope if slope > 1e-12 else 1e-12)


def steady_power_w(kelvin: float) -> float:
    """The heater power that holds a temperature.

    Log-log, because Q spans five decades while T spans one and a half -- and
    because this is the one curve inverted in both directions, so a kink in it
    is a kink in the steady state and in the gain at once.
    """
    return math.exp(_interp(math.log(max(kelvin, 1e-9)), _LOG_T, _LOG_Q))


def steady_temperature_k(watts: float) -> float:
    """The temperature a heater power settles at.  The inverse of the above.

    Monotone by construction -- checked when the table is generated -- so this
    is an interpolation and not a root find.
    """
    if watts <= 0.0:
        return _T[0]
    return math.exp(_interp(math.log(watts), _LOG_Q, _LOG_T))


# -- the residual, and its band -------------------------------------------
#
# PID_PLAN.md section 3.  The monitor and the supervisor judge the cryostat by
# ONE number and they call THESE TWO FUNCTIONS to get it, so that they cannot
# disagree about what typical means -- only about what to do about it.
#
# In watts at the sample node, because every measured disturbance on this
# cryostat is a power -- the campaign drift is 0.281 mW/day and the 2026-09-10
# fault was -4.9 mW -- while the gain runs 0.35 to 13.3 K/% across the band.  A
# kelvin threshold is two different thresholds at the two ends of this
# cryostat, and it is valid only at a hold; this one is valid during a sweep,
# which is where the loop spends the interesting part of its life.


def conductance_w(sample_k: float, sink_k: float | None = None) -> float:
    """``Lambda(T_s) - Lambda(T_c)``: the power the link carries, in W.

    With ``sink_k`` omitted this is the table's own ``q`` -- the sample sinking
    to the coldplate where the settled dwells put it, which is what
    :func:`steady_power_w` answers.  Pass the MEASURED coldplate and the
    difference is corrected for, because the coldplate does not always sit on
    its locus: it lags by ``TAU_BATH_S`` during a transient and it rises when
    the compressor is unwell, and both are cases the monitor exists to tell
    apart.

    The correction is linear in ``Lambda'`` at the midpoint, and it is small in
    kelvin and not small in watts: the coldplate moves 2.3 K across a range the
    sample moves 190 K over, but ``Lambda'`` at 6.6 K is NINE TIMES ``Lambda'``
    at 118 K, so 100 mK of sink is worth 1.5 mW where 100 mK of sample is worth
    0.17 mW.  That asymmetry is why the sink term is the largest one in a
    settled band at the warm end.
    """
    q = steady_power_w(sample_k)
    if sink_k is None:
        return q
    locus = coldplate_k(sample_k)
    if sink_k == locus:
        return q
    return q + lambda_slope_w_per_k(0.5 * (locus + sink_k)) * (locus - sink_k)


def missing_power_w(sample_k: float, dt_dt_k_per_s: float,
                    sink_k: float, pct: float) -> float:
    """``dQ``: the watts the heater is not delivering.  The residual.

    ::

        dQ = C(T_s) dT_s/dt + [Lambda(T_s) - Lambda(T_c)] - P(u)      [W]

    **Sign: NEGATIVE means power is missing**, which is the direction the name
    is about and the direction of every fault measured on this cryostat.  The
    2026-09-10 event reads **-4.9 mW**: a few tenths of an ohm appeared in
    series with the heater, less heat arrived than ``P(u)`` claimed, and the
    sample cooled.  Positive is the opposite and rarer -- heat arriving that
    the model does not account for.

    Zero at every settled point the model was fitted to, by construction, and
    that is the whole trick: at a hold ``dT/dt`` is zero and this reduces to
    "does the heater power match the steady-state curve", while during a sweep
    the heat capacity term carries the difference.  **A kelvin check cannot do
    the second half.**

    **There is no D(t) term and its absence is a measurement.**  PID_PLAN.md
    section 3 wrote the residual with a fitted campaign drift in it.
    REFIT_PLAN.md section 7.3 then took the drift back out of the shipped fit:
    inside one undisturbed epoch there is no drift to find, and what looks like
    a rate across the campaign is a staircase of somebody handling the heater
    wiring.  So nothing here predicts the drift -- and because nothing predicts
    it, :func:`sigma_q_w` carries ALL of it rather than a quarter of it.
    """
    return (heat_capacity_j_per_k(sample_k) * dt_dt_k_per_s
            + conductance_w(sample_k, sink_k)
            - power_w(pct))


def days_since_gauge(t: float) -> float:
    """Days from the day the level was gauged to unix time ``t``.  Never below 0.

    Clamped at zero because a residual computed against an archive window
    recorded BEFORE the gauge is not entitled to a narrower band than one
    recorded after it -- the level was no better known then, it was differently
    known, and the sign of the difference is exactly what section 7.3 says
    cannot be predicted.
    """
    return max(0.0, (t - DRIFT_T0_UNIX) / 86400.0)


def sigma_q_terms(sample_k: float, pct: float, t: float,
                  dt_dt_k_per_s: float = 0.0) -> dict:
    """Every term of the band separately, in W.  One sigma each.

    The monitor reports which term dominates when it warns, because "3.2 mW out
    of band" is not a sentence anybody can act on and "3.2 mW, and the band is
    nine days of undisturbed drift" is.
    """
    slope = lambda_slope_w_per_k(sample_k)
    sink = lambda_slope_w_per_k(coldplate_k(sample_k))
    watts = power_w(pct)
    return {
        # The sink, and it is the biggest one at a settled warm hold.
        "sink": TC_RMS_K * sink,
        # What a settled temperature is known to, and the building's day.
        "thermometry": SIGMA_TINF_K * slope,
        "diurnal": DIURNAL_K * slope,
        # Where the curve sits, inside one epoch: section 1's own scoreboard.
        "model": SIGMA_MODEL_K * slope,
        # A fraction of the DELIVERED power per day, so it vanishes with the
        # heater -- the cold end refuses a constant parasitic watt three ways.
        "drift": (DRIFT_W_PER_DAY * watts / DRIFT_REF_W) * days_since_gauge(t),
        # Zero at a hold; ~70 mW at 5 K/min and 118 K, of which this is 3 %.
        # Without it every sweep warns, which is PID_PLAN.md section 3's point.
        "dynamic": SIGMA_C_FRAC * heat_capacity_j_per_k(sample_k)
        * abs(dt_dt_k_per_s),
    }


#: The terms that can move inside an alarm's own timescale.  Everything else in
#: the band is a slow term, and a judge that works on the CHANGE in the
#: residual rather than on its level has already removed those.
#:
#: **This split is what lets one calibration last a whole cooldown** (Jeff,
#: 2026-09-14: recalibrate at most once per cooldown).  ``drift`` grows at
#: 0.29 mW/day at 118 K with nothing subtracting it, so two months after a
#: gauge the full band is 52 mW -- 31 K, which is wider than any fault worth
#: naming.  Referenced to a trailing baseline instead, the drift is absorbed
#: along with the calibration bias and what is left does not grow at all.
#:
#: The same instruction says why that is enough: **real faults are
#: unmistakable.**  The 2026-09-10 event moved the sample 3 K.  Nothing here is
#: trying to resolve a milliwatt.
FAST_TERMS = ("sink", "thermometry", "model", "dynamic")


def sigma_q_fast_w(sample_k: float, pct: float,
                   dt_dt_k_per_s: float = 0.0) -> float:
    """One sigma on a CHANGE in :func:`missing_power_w`, in W.

    The band for a judge that watches the residual move rather than the
    residual's level: :data:`FAST_TERMS` only, so no drift and no calibration.
    **It takes no ``t``, and that is the point** -- it is the same number on the
    day of a gauge and two months later, which is what makes one calibration
    per cooldown workable.

    3 sigma of this is 1.4 mW at 118 K settled and 6.7 mW at 5 K/min, against a
    2026-09-10 fault of -4.9 mW and a fault threshold near 8 mW.  The consumer
    is responsible for the baseline: it must be slow against a fault and fast
    against the drift (hours, not minutes and not days), and it must FREEZE
    while the verdict is not typical or it learns the fault it is judging.
    """
    terms = sigma_q_terms(sample_k, pct, DRIFT_T0_UNIX, dt_dt_k_per_s)
    return math.sqrt(sum(terms[k] ** 2 for k in FAST_TERMS))


def sigma_q_w(sample_k: float, pct: float, t: float,
              dt_dt_k_per_s: float = 0.0) -> float:
    """One sigma on :func:`missing_power_w`, in W.  Quadrature of the terms.

    Settled, on the day it was gauged, 3 sigma of this is **1.4 mW at 118 K**
    and between 0.41 and 0.87 K across 10-180 K at the local gain -- so the
    band is about a kelvin everywhere, which is where Jeff's "warn at a kelvin"
    lands when it is arrived at from measured terms instead of chosen.  Ten
    days later the same band is 8.8 mW, because the drift is the term that
    grows and nothing subtracts it.

    **`t` is required and it is unix seconds.**  A band that silently defaults
    to day zero is a band that gets narrower the longer nobody re-gauges, which
    is backwards.

    What is NOT in here is :func:`bias_q_w`.  Read its docstring before adding
    it: the two are different quantities and quadrature is the wrong operation
    on them.
    """
    terms = sigma_q_terms(sample_k, pct, t, dt_dt_k_per_s)
    return math.sqrt(sum(v * v for v in terms.values()))


def bias_q_w(pct: float) -> float:
    """The CALIBRATION offset on ``dQ``, in W.  Deliberately not in the band.

    ``DELTA_P_FRAC`` of the delivered power: how far the whole curve's level
    may sit from the truth because the heater circuit delivers a little more or
    less than ``P(u)`` says.  4.7 mW at 118 K, which is 2.8 K.

    **It is a constant, not a fluctuation.**  It changes when somebody handles
    the heater wiring -- three such events are measured in REFIT_PLAN.md
    section 7.2, all of them a few tenths of an ohm in series with a 75.5 ohm
    heater -- and between those events it does not change at all.  Add it to
    :func:`sigma_q_w` in quadrature and 3 sigma at 118 K becomes 14 mW, which
    is larger than the fault threshold and three times the 2026-09-10 event
    that phase 2's replay requires the monitor to catch.  A band carrying a
    systematic that cannot move inside thirty minutes cannot see a fault that
    happens inside thirty minutes.

    So it is exported under its own name, for the three consumers that actually
    feel it:

    * the monitor's ABSOLUTE residual -- whose answer is a trailing baseline,
      not a wider alarm;
    * the velocity feedforward, which is open loop by definition;
    * the fault ramp-down through the inverse curve, which is open loop on
      purpose (safety rule 3: the fault may be the sensor).  0.7 % of full
      power is a few kelvin of terminal error on an emergency descent to base,
      and an emergency descent to base does not care.

    **The closed loop never sees it.**  A PI controller's integral action
    absorbs a constant power offset exactly, which is why measuring the heater
    circuit four-wire is not on the critical path to a working software PID.
    """
    return DELTA_P_FRAC * power_w(pct)


class FittedResponse:
    """A drop-in for :class:`~ltspm3.model.sim_response.ThermalModel`, fitted.

    The interface the simulator needs is four names -- ``pct``, ``temperature``,
    ``advance`` and ``observe`` -- and it is duck-typed by
    :class:`~lschart.instruments.sim.SimulatedCryostat`, which is what keeps
    invariant 1 intact: ``lschart`` never learns that this class exists.
    """

    def __init__(self, params: FittedParams | None = None, *,
                 start_k: float | None = None, start_pct: float = 0.0) -> None:
        self.p = params or FittedParams()
        self.pct = float(start_pct)
        self._t = float(self.steady_state(start_pct) if start_k is None else start_k)

    # -- the model --------------------------------------------------------

    @property
    def temperature(self) -> float:
        return self._t

    def steady_state(self, pct: float) -> float:
        return steady_temperature_k(power_w(pct))

    def percent_for(self, kelvin: float) -> float:
        """What to type to hold a temperature.  The operator's question."""
        return percent_for_power(steady_power_w(kelvin))

    def local_gain(self, pct: float) -> float:
        """``dT/d(pct)`` in K/% -- 0.3 at 10 K and 13 at 110 K, which is why a
        step that is a trim up there is the whole range down here."""
        h = max(pct * 1e-3, 1e-3)
        return (self.steady_state(pct + h) - self.steady_state(max(pct - h, 0.0))) / (
            (pct + h) - max(pct - h, 0.0))

    def tau_at(self, kelvin: float | None = None) -> float:
        return tau_s(self._t if kelvin is None else kelvin)

    #: Substeps are capped here.  Past a few dozen the answer has stopped
    #: moving and the cost has not, and the case that needs many is the cold
    #: end, where tau is 0.01 s against a 2 s cadence and the rung is settled
    #: several hundred time constants before the next sample arrives anyway.
    MAX_SUBSTEPS = 64

    #: Substep whenever one step would cover more than this much of a time
    #: constant.  Exponential Euler is exact for the *linearised* relaxation, so
    #: a single huge step lands on the tangent's fixed point rather than the
    #: curve's: one 20,000 s step from 70 K toward 110 K stops at 103, because
    #: Lambda' at 70 K is not Lambda' at 110 K.  Re-linearising four times per
    #: time constant costs nothing and removes the error.
    SUBSTEP_FRACTION = 0.25

    def advance(self, dt: float) -> None:
        if dt <= 0:
            return
        q_in = power_w(self.pct)
        n = max(1, min(self.MAX_SUBSTEPS,
                       int(dt / (self.SUBSTEP_FRACTION * tau_s(self._t))) + 1))
        step = dt / n
        for _ in range(n):
            t = self._t
            net = q_in - steady_power_w(t)
            tau = tau_s(t)
            # Exponential Euler, as the fit itself integrates: exact for the
            # linearised relaxation and stable at any step size.  Its fixed
            # point is where the net power is zero, which is the fitted steady
            # state and not an artefact of the integrator.
            t += (net / heat_capacity_j_per_k(t)) * tau * (1.0 - math.exp(-step / tau))
            # The table clamps rather than extrapolating, so keep the state
            # inside it: past the ends the curves are flat and the physics is
            # fiction.
            self._t = min(max(t, T_MIN_K), T_MAX_K)

    def observe(self, rng: random.Random) -> float:
        t = self._t
        sigma = max(self.p.noise_floor_k, self.p.noise_quadratic * t * t)
        noisy = t + rng.gauss(0.0, sigma)
        q = self.p.quantum_k
        return round(noisy / q) * q if q > 0 else noisy


def fitted_cryostat(*, start_k: float | None = None, start_pct: float = 0.0, **kw):
    """A :class:`SimulatedCryostat` running the fitted model.

    The cross-channel couplings come from :mod:`ltspm3.model.sim_response`: they were
    measured from the reference logs and the ODE fit says nothing about them.
    """
    from lschart.instruments.sim import SimulatedCryostat

    from .sim_response import LTSPM3_AUX_COUPLING

    response = FittedResponse(start_k=start_k, start_pct=start_pct)
    return SimulatedCryostat(response=response, start_k=response.temperature,
                             aux_coupling=LTSPM3_AUX_COUPLING, **kw)
