"""The simulated cryostat, driven by the fitted ODE instead of a two-pole lag.

``sim_response.ThermalModel`` was the best available when it was written and is
now the second best.  It carries **one** time constant -- 620 s, inferred from a
single clean step at 137 K -- onto a steady state interpolated from the CD10
percent-to-kelvin table.  The 43 h sweep of 2026-09 and the ODE fitted to it
say both halves are wrong away from that one point:

* ``tau`` is not a constant.  ``tau = C/Lambda'`` runs from **under a second at
  10 K to about 490 s at 110 K** -- a factor of a thousand, because C falls
  steeply as the cryostat cools while the link's conductance does not.
* the steady state is out by up to **17 K** in the middle, where CD10 had two
  points twenty percentage points apart and the curve between them was a power
  law doing the best it could.

Neither error is visible in a control test that sits at one temperature, which
is why this went unnoticed: at 137 K the two models agree, and that is where
almost everything was tested.  It is very visible in a *sweep*, which is the
one thing that crosses the whole range -- rehearse a 30-rung ladder against the
old response and two thirds of the rungs come back cut off mid-relaxation, none
of it telling you anything about the cryostat.

What this integrates
--------------------

The same equation the fit was fitted with::

    C(T) dT/dt = Q(u) - [Lambda(T) - Lambda(T_c)]

with ``Q(u) = (G V_fs u/100)^2 / R`` -- exact, the actuator chain has nothing
to fit -- and exponential Euler, ``T += g tau (1 - exp(-dt/tau))``, which is
exact for the linearised relaxation and unconditionally stable.  Stability is
not a nicety here: C falls so steeply at the cold end that an explicit step
goes unstable there long before the interesting physics does, and the tests
drive this with a virtual clock at wildly varying dt.

The four curves come from :mod:`ltspm3._fitted_table`, which is generated by
``analysis/export_response.py`` and checked in.  The fit itself needs scipy,
the 43 h sweep and a couple of minutes; this needs the standard library.

What it still simplifies
------------------------

**The coldplate follows the sample along its settled locus**, rather than
lagging it.  ``T_c`` is interpolated against sample temperature from the
settled dwells, so the steady state is exactly the fitted one, while during a
transient the real coldplate lags by about 175 s (``analysis/bath.py``).  That
is worth knowing before reading a simulated transient closely, and it is not
worth fixing for a rehearsal: the coldplate moves 2.3 K across the range the
sample moves 190 K over.

Outside 4.7-195 K the table **clamps**.  A simulator that quietly extrapolates
a fitted curve is inventing a cryostat, and inventing one is how a rehearsal
comes to disagree with the afternoon it was rehearsing.
"""

from __future__ import annotations

import math
import random
from bisect import bisect_right
from dataclasses import dataclass

from ._fitted_table import GAIN, R_OHM, T_MAX_K, T_MIN_K, TABLE, V_FS

__all__ = ["FittedParams", "FittedResponse", "power_w", "percent_for_power"]


def power_w(pct: float) -> float:
    """Heater watts for a commanded percent.  Exact: the heater is a resistor.

    The 218's analog output is a voltage into a stable 75.5 ohm heater, so
    ``P = V^2/R`` and there is nothing here that varies with temperature or
    that anyone has to fit.  Every difficulty on this cryostat lives in T(P).
    """
    return (GAIN * V_FS * max(pct, 0.0) / 100.0) ** 2 / R_OHM


def percent_for_power(watts: float) -> float:
    if watts <= 0.0:
        return 0.0
    return 100.0 * math.sqrt(watts * R_OHM) / (GAIN * V_FS)


@dataclass
class FittedParams:
    """The parts of the simulated sensor that are not the thermal model.

    Measured by 3-point local detrending over cd9+cd10, and shared with
    ``ResponseParams`` on purpose -- the thermometer did not change when the
    model did.
    """

    noise_floor_k: float = 0.0018      # rms at low T
    noise_quadratic: float = 1.36e-6   # rms = this * T**2
    quantum_k: float = 0.001           # reported resolution


# The table, unpacked once into parallel lists.  Logs are precomputed because
# every interpolation here is log-log -- the curves are power laws over most of
# their range, and interpolating them linearly in T would put visible kinks in
# a quantity the fit went to some trouble to make smooth.
_T = [row[0] for row in TABLE]
_LOG_T = [math.log(t) for t in _T]
#: ``Q(T) = Lambda(T) - Lambda(T_c(T))``, the power that holds each temperature.
#: The table carries this **evaluated** rather than carrying Lambda, and that is
#: not an optimisation: Lambda is 2.38 W at the cold end where Q is 8 mW, so
#: reconstructing Q by subtracting two interpolated Lambdas loses five
#: significant figures -- and the T_c term falls off the bottom of any grid that
#: starts at the coldest sample temperature, because the coldplate is colder
#: still.  Doing it that way put every steady state below 8 K about 0.2 K too
#: warm, which is four times the fit's own residual.
_LOG_Q = [math.log(row[1]) for row in TABLE]
_LOG_SLOPE = [math.log(row[2]) for row in TABLE]
_LOG_CAP = [math.log(row[3]) for row in TABLE]
_TC = [row[4] for row in TABLE]


def _interp(x: float, xs: list[float], ys: list[float]) -> float:
    """Linear in the given coordinates, clamped at both ends."""
    if x <= xs[0]:
        return ys[0]
    if x >= xs[-1]:
        return ys[-1]
    i = bisect_right(xs, x) - 1
    x0, x1 = xs[i], xs[i + 1]
    y0, y1 = ys[i], ys[i + 1]
    return y0 if x1 == x0 else y0 + (y1 - y0) * (x - x0) / (x1 - x0)


def _log_interp(kelvin: float, log_ys: list[float]) -> float:
    return math.exp(_interp(math.log(max(kelvin, 1e-9)), _LOG_T, log_ys))


def lambda_slope_w_per_k(kelvin: float) -> float:
    """``Lambda'(T) = k(T) A/L``, in W/K."""
    return _log_interp(kelvin, _LOG_SLOPE)


def heat_capacity_j_per_k(kelvin: float) -> float:
    return _log_interp(kelvin, _LOG_CAP)


def coldplate_k(kelvin: float) -> float:
    """The coldplate the sample is sinking to, at this sample temperature.

    Measured, not assumed: 4.8 K with the heater off and 6.9 K at 180 K.  A
    constant bath here would put the whole 2.1 K of it into ``Lambda``.
    """
    return _interp(kelvin, _T, _TC)


def tau_s(kelvin: float) -> float:
    """The local time constant, ``C/Lambda'``.  0.01 s at 4.9 K, 619 s at 195 K."""
    slope = lambda_slope_w_per_k(kelvin)
    return heat_capacity_j_per_k(kelvin) / (slope if slope > 1e-12 else 1e-12)


def steady_power_w(kelvin: float) -> float:
    """The heater power that holds a temperature.

    Log-log, because Q spans five decades while T spans one and a half -- and
    because this is the one curve inverted in both directions, so a kink in it
    is a kink in the steady state and in the gain at once.
    """
    return math.exp(_interp(math.log(max(kelvin, 1e-9)), _LOG_T, _LOG_Q))


def steady_temperature_k(watts: float) -> float:
    """The temperature a heater power settles at.  The inverse of the above.

    Monotone by construction -- checked when the table is generated -- so this
    is an interpolation and not a root find.
    """
    if watts <= 0.0:
        return _T[0]
    return math.exp(_interp(math.log(watts), _LOG_Q, _LOG_T))


class FittedResponse:
    """A drop-in for :class:`~ltspm3.sim_response.ThermalModel`, fitted.

    The interface the simulator needs is four names -- ``pct``, ``temperature``,
    ``advance`` and ``observe`` -- and it is duck-typed by
    :class:`~lschart.instruments.sim.SimulatedCryostat`, which is what keeps
    invariant 1 intact: ``lschart`` never learns that this class exists.
    """

    def __init__(self, params: FittedParams | None = None, *,
                 start_k: float | None = None, start_pct: float = 0.0) -> None:
        self.p = params or FittedParams()
        self.pct = float(start_pct)
        self._t = float(self.steady_state(start_pct) if start_k is None else start_k)

    # -- the model --------------------------------------------------------

    @property
    def temperature(self) -> float:
        return self._t

    def steady_state(self, pct: float) -> float:
        return steady_temperature_k(power_w(pct))

    def percent_for(self, kelvin: float) -> float:
        """What to type to hold a temperature.  The operator's question."""
        return percent_for_power(steady_power_w(kelvin))

    def local_gain(self, pct: float) -> float:
        """``dT/d(pct)`` in K/% -- 0.3 at 10 K and 13 at 110 K, which is why a
        step that is a trim up there is the whole range down here."""
        h = max(pct * 1e-3, 1e-3)
        return (self.steady_state(pct + h) - self.steady_state(max(pct - h, 0.0))) / (
            (pct + h) - max(pct - h, 0.0))

    def tau_at(self, kelvin: float | None = None) -> float:
        return tau_s(self._t if kelvin is None else kelvin)

    #: Substeps are capped here.  Past a few dozen the answer has stopped
    #: moving and the cost has not, and the case that needs many is the cold
    #: end, where tau is 0.01 s against a 2 s cadence and the rung is settled
    #: several hundred time constants before the next sample arrives anyway.
    MAX_SUBSTEPS = 64

    #: Substep whenever one step would cover more than this much of a time
    #: constant.  Exponential Euler is exact for the *linearised* relaxation, so
    #: a single huge step lands on the tangent's fixed point rather than the
    #: curve's: one 20,000 s step from 70 K toward 110 K stops at 103, because
    #: Lambda' at 70 K is not Lambda' at 110 K.  Re-linearising four times per
    #: time constant costs nothing and removes the error.
    SUBSTEP_FRACTION = 0.25

    def advance(self, dt: float) -> None:
        if dt <= 0:
            return
        q_in = power_w(self.pct)
        n = max(1, min(self.MAX_SUBSTEPS,
                       int(dt / (self.SUBSTEP_FRACTION * tau_s(self._t))) + 1))
        step = dt / n
        for _ in range(n):
            t = self._t
            net = q_in - steady_power_w(t)
            tau = tau_s(t)
            # Exponential Euler, as the fit itself integrates: exact for the
            # linearised relaxation and stable at any step size.  Its fixed
            # point is where the net power is zero, which is the fitted steady
            # state and not an artefact of the integrator.
            t += (net / heat_capacity_j_per_k(t)) * tau * (1.0 - math.exp(-step / tau))
            # The table clamps rather than extrapolating, so keep the state
            # inside it: past the ends the curves are flat and the physics is
            # fiction.
            self._t = min(max(t, T_MIN_K), T_MAX_K)

    def observe(self, rng: random.Random) -> float:
        t = self._t
        sigma = max(self.p.noise_floor_k, self.p.noise_quadratic * t * t)
        noisy = t + rng.gauss(0.0, sigma)
        q = self.p.quantum_k
        return round(noisy / q) * q if q > 0 else noisy


def fitted_cryostat(*, start_k: float | None = None, start_pct: float = 0.0, **kw):
    """A :class:`SimulatedCryostat` running the fitted model.

    The cross-channel couplings come from :mod:`ltspm3.sim_response`: they were
    measured from the reference logs and the ODE fit says nothing about them.
    """
    from lschart.instruments.sim import SimulatedCryostat

    from .sim_response import LTSPM3_AUX_COUPLING

    response = FittedResponse(start_k=start_k, start_pct=start_pct)
    return SimulatedCryostat(response=response, start_k=response.temperature,
                             aux_coupling=LTSPM3_AUX_COUPLING, **kw)
